# ===== KONSTANTES ===== Konstante = mainīgais, kura vērtība programmā netiek mainīta. Konstantes vienmēr raksta ar lielajiem burtiem un apakšsvītrām, ja nepieciešams. Piemēram: PI = 3.14159 konstantes parasti definē faila sākumā, lai tās būtu viegli atrodamas un redzamas. Šajā gadījumā mēs definējam dažādus konvertēšanas koeficientus, kas tiks izmantoti vēlāk programmā, lai veiktu vienību konvertēšanu. konstntes lieto lai padarītu kodu skaidrāku un vieglāk uztveramu, jo tās nosaukumi var būt aprakstoši un palīdzēt saprast, ko konkrētā vērtība nozīmē. Piemēram, KM_TO_MI skaidri norāda, ka tas ir koeficients, kas tiek izmantots, lai konvertētu kilometrus uz jūdzēm. Ja mainās lielums konstanti maina tikai vienā vietā. Nav jāmeklē pa visu kodu un jāmaina katru reizi, kad tā tiek izmantota. Tas samazina kļūdu iespējamību un padara kodu vieglāk uzturamu. Ja, piemēram, mainās konvertēšanas koeficients no USD uz EUR, tad mēs tikai mainām vērtību USD_TO_EUR konstantē, un visa programma automātiski izmanto jauno koeficientu bez nepieciešamības meklēt un mainīt katru atsevišķo konvertēšanas operāciju. Tas ir īpaši noderīgi lielākos projektos, kur konvertēšanas koeficienti var tikt izmantoti daudzās vietās.
KM_TO_MI = 0.621371   
KG_TO_LB = 2.20462
L_TO_GAL = 0.264172
USD_TO_EUR = 0.84235020

# ===== IZVĒLNE ===== Izvēlne ir saraksts ar iespējām, no kurām lietotājs var izvēlēties. Šajā gadījumā mēs piedāvājam dažādus vienību konvertēšanas veidus. Lietotājs ievada numuru, kas atbilst viņa izvēlei, un programma veic attiecīgo konvertēšanu.
print("=== Vienību konvertors ===")
print("1 - km → jūdzes") 
print("2 - jūdzes → km")
print("3 - kg → mārciņas")
print("4 - mārciņas → kg")
print("5 - litri → galoni")
print("6 - galoni → litri")
print("7 - USD → EUR")
print("8 - EUR → USD")

choice = input("Izvēlies numuru: ")   # Šī rindiņa ļauj lietotājam ievadīt savu izvēli, un tā tiek saglabāta mainīgajā "choice". Lietotājs var ievadīt skaitli no 1 līdz 8, atkarībā no tā, kādu konvertēšanu viņš vēlas veikt. Pēc tam programma izmantos šo izvēli, lai noteiktu, kādu konvertēšanu veikt un kādus koeficientus izmantot aprēķinos.

# ===== SKAITĻA IEVADE =====
try: # mēģina izpildīt nākamo kodu, un ja rodas kļūda, tā tiek apstrādāta except blokā. Šajā gadījumā mēs mēģinām pārvērst lietotāja ievadi par skaitli ar peldošo komatu (float). Ja lietotājs ievada nepareizu vērtību, piemēram, tekstu vai simbolus, kas nav skaitļi, programma izraisīs ValueError izņēmumu. Tāpēc mēs izmantojam try-except bloku, lai apstrādātu šo izņēmumu un izvairītos no programmas avārijas. Ja tiek izsaukts ValueError, programma izvadīs ziņojumu "Kļūda — jāievada skaitlis!" un pēc tam tiks pārtraukta ar exit() funkciju. Tas nodrošina, ka programma darbojas tikai ar derīgām skaitliskām vērtībām un sniedz lietotājam atgriezenisko saiti par nepareizu ievadi.
    value = float(input("Ievadi vērtību: "))  # Šī rindiņa ļauj lietotājam ievadīt vērtību, ko viņš vēlas konvertēt. Ievade tiek pārvērsta par decimāldaļas skaitli (float), lai varētu veikt matemātiskās operācijas. Ja lietotājs ievada nepareizu vērtību, piemēram, tekstu vai simbolus, kas nav skaitļi, programma izraisīs ValueError izņēmumu. Tāpēc mēs izmantojam try-except bloku, lai apstrādātu šo izņēmumu un izvairītos no programmas avārijas. Ja tiek izsaukts ValueError, programma izvadīs ziņojumu "Kļūda — jāievada skaitlis!" un pēc tam tiks pārtraukta ar exit() funkciju. Tas nodrošina, ka programma darbojas tikai ar derīgām skaitliskām vērtībām un sniedz lietotājam atgriezenisko saiti par nepareizu ievadi. 
except ValueError: 
    print("Kļūda — jāievada skaitlis!")
    exit()

# ===== APRĒĶINI =====
if choice == "1": # if bloks tiek izmantots, lai pārbaudītu, vai lietotāja izvēle atbilst konkrētai opcijai. Šajā gadījumā mēs pārbaudām, vai choice ir vienāds ar "1", kas atbilst km → jūdzes konvertēšanai. Ja izvēle ir "1", programma veic konvertēšanu, reizinot ievadīto vērtību ar KM_TO_MI konstantu, un izvada rezultātu formātā "X km = Y mi". Ja izvēle nav "1", programma turpina pārbaudīt citas iespējas ar elif blokiem. "1" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "1", nevis ar skaitli 1. Ja lietotājs ievada "1", programma veiks km → jūdzes konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value * KM_TO_MI # Šī rindiņa veic konvertēšanu, reizinot ievadīto vērtību (value) ar KM_TO_MI konstantu, kas ir konvertēšanas koeficients no kilometriem uz jūdzēm. Rezultāts tiek saglabāts mainīgajā "result". Piemēram, ja lietotājs ievada 10 km, tad result būs 10 * 0.621371 = 6.21371 mi.
    print(f"{value:.2f} km = {result:.2f} mi") # Šī rindiņa izvada rezultātu formātā "X km = Y mi", kur X ir ievadītā vērtība (value) ar divām zīmēm aiz komata, un Y ir konvertētā vērtība (result) ar divām zīmēm aiz komata. f-string sintakse ļauj ērti formatēt tekstu un mainīgos vienā rindiņā. Piemēram, ja value ir 10 un result ir 6.21371, tad izvadītais teksts būs "10.00 km = 6.21 mi". Tas padara rezultātu skaidru un viegli saprotamu lietotājam.

elif choice == "2": # Šis elif bloks pārbauda, vai lietotāja izvēle ir "2", kas atbilst jūdzes → km konvertēšanai. Ja izvēle ir "2", programma veic konvertēšanu, dalot ievadīto vērtību ar KM_TO_MI konstantu, un izvada rezultātu formātā "X mi = Y km". Ja izvēle nav "2", programma turpina pārbaudīt citas iespējas ar elif blokiem. "2" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "2", nevis ar skaitli 2. Ja lietotājs ievada "2", programma veiks jūdzes → km konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value / KM_TO_MI # Šī rindiņa veic konvertēšanu, dalot ievadīto vērtību (value) ar KM_TO_MI konstantu, kas ir konvertēšanas koeficients no kilometriem uz jūdzēm. Rezultāts tiek saglabāts mainīgajā "result". Piemēram, ja lietotājs ievada 10 mi, tad result būs 10 / 0.621371 = 16.0934 km.
    print(f"{value:.2f} mi = {result:.2f} km")

elif choice == "3": # Šis elif bloks pārbauda, vai lietotāja izvēle ir "3", kas atbilst kg → mārciņas konvertēšanai. Ja izvēle ir "3", programma veic konvertēšanu, reizinot ievadīto vērtību ar KG_TO_LB konstantu, un izvada rezultātu formātā "X kg = Y lb". Ja izvēle nav "3", programma turpina pārbaudīt citas iespējas ar elif blokiem. "3" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "3", nevis ar skaitli 3. Ja lietotājs ievada "3", programma veiks kg → mārciņas konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value * KG_TO_LB # Šī rindiņa veic konvertēšanu, reizinot ievadīto vērtību (value) ar KG_TO_LB konstantu, kas ir konvertēšanas koeficients no kilogramiem uz mārciņām. Rezultāts tiek saglabāts mainīgajā "result". Piemēram, ja lietotājs ievada 10 kg, tad result būs 10 * 2.20462 = 22.0462 lb.
    print(f"{value:.2f} kg = {result:.2f} lb") # Šī rindiņa izvada rezultātu formātā "X kg = Y lb", kur X ir ievadītā vērtība (value) ar divām zīmēm aiz komata, un Y ir konvertētā vērtība (result) ar divām zīmēm aiz komata. f-string sintakse ļauj ērti formatēt tekstu un mainīgos vienā rindiņā. Piemēram, ja value ir 10 un result ir 22.0462, tad izvadītais teksts būs "10.00 kg = 22.05 lb". Tas padara rezultātu skaidru un viegli saprotamu lietotājam.

elif choice == "4": # Šis elif bloks pārbauda, vai lietotāja izvēle ir "4", kas atbilst mārciņas → kg konvertēšanai. Ja izvēle ir "4", programma veic konvertēšanu, dalot ievadīto vērtību ar KG_TO_LB konstantu, un izvada rezultātu formātā "X lb = Y kg". Ja izvēle nav "4", programma turpina pārbaudīt citas iespējas ar elif blokiem. "4" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "4", nevis ar skaitli 4. Ja lietotājs ievada "4", programma veiks mārciņas → kg konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value / KG_TO_LB # Šī rindiņa veic konvertēšanu, dalot ievadīto vērtību (value) ar KG_TO_LB konstantu, kas ir konvertēšanas koeficients no kilogramiem uz mārciņām. Rezultāts tiek saglabāts mainīgajā "result". Piemēram, ja lietotājs ievada 10 lb, tad result būs 10 / 2.20462 = 4.53592 kg.
    print(f"{value:.2f} lb = {result:.2f} kg") # Šī rindiņa izvada rezultātu formātā "X lb = Y kg", kur X ir ievadītā vērtība (value) ar divām zīmēm aiz komata, un Y ir konvertētā vērtība (result) ar divām zīmēm aiz komata. f-string sintakse ļauj ērti formatēt tekstu un mainīgos vienā rindiņā. Piemēram, ja value ir 10 un result ir 4.53592, tad izvadītais teksts būs "10.00 lb = 4.54 kg". Tas padara rezultātu skaidru un viegli saprotamu lietotājam.

elif choice == "5": # Šis elif bloks pārbauda, vai lietotāja izvēle ir "5", kas atbilst litri → galoni konvertēšanai. Ja izvēle ir "5", programma veic konvertēšanu, reizinot ievadīto vērtību ar L_TO_GAL konstantu, un izvada rezultātu formātā "X L = Y gal". Ja izvēle nav "5", programma turpina pārbaudīt citas iespējas ar elif blokiem. "5" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "5", nevis ar skaitli 5. Ja lietotājs ievada "5", programma veiks litri → galoni konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value * L_TO_GAL # Šī rindiņa veic konvertēšanu, reizinot ievadīto vērtību (value) ar L_TO_GAL konstantu, kas ir konvertēšanas koeficients no litriem uz galoniem. Rezultāts tiek saglabāts mainīgajā "result". Piemēram, ja lietotājs ievada 10 L, tad result būs 10 * 0.264172 = 2.64172 gal.
    print(f"{value:.2f} L = {result:.2f} gal")  # Šī rindiņa izvada rezultātu formātā "X L = Y gal", kur X ir ievadītā vērtība (value) ar divām zīmēm aiz komata, un Y ir konvertētā vērtība (result) ar divām zīmēm aiz komata. f-string sintakse ļauj ērti formatēt tekstu un mainīgos vienā rindiņā. Piemēram, ja value ir 10 un result ir 2.64172, tad izvadītais teksts būs "10.00 L = 2.64 gal". Tas padara rezultātu skaidru un viegli saprotamu lietotājam.

elif choice == "6": # Šis elif bloks pārbauda, vai lietotāja izvēle ir "6", kas atbilst galoni → litri konvertēšanai. Ja izvēle ir "6", programma veic konvertēšanu, dalot ievadīto vērtību ar L_TO_GAL konstantu, un izvada rezultātu formātā "X gal = Y L". Ja izvēle nav "6", programma turpina pārbaudīt citas iespējas ar elif blokiem. "6" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "6", nevis ar skaitli 6. Ja lietotājs ievada "6", programma veiks galoni → litri konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value / L_TO_GAL 
    print(f"{value:.2f} gal = {result:.2f} L") # Šī rindiņa izvada rezultātu formātā "X gal = Y L", kur X ir ievadītā vērtība (value) ar divām zīmēm aiz komata, un Y ir konvertētā vērtība (result) ar divām zīmēm aiz komata. f-string sintakse ļauj ērti formatēt tekstu un mainīgos vienā rindiņā. Piemēram, ja value ir 10 un result ir 37.8541, tad izvadītais teksts būs "10.00 gal = 37.85 L". Tas padara rezultātu skaidru un viegli saprotamu lietotājam.

elif choice == "7": # Šis elif bloks pārbauda, vai lietotāja izvēle ir "7", kas atbilst USD → EUR konvertēšanai. Ja izvēle ir "7", programma veic konvertēšanu, reizinot ievadīto vērtību ar USD_TO_EUR konstantu, un izvada rezultātu formātā "X USD = Y EUR". Ja izvēle nav "7", programma turpina pārbaudīt citas iespējas ar elif blokiem. "7" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "7", nevis ar skaitli 7. Ja lietotājs ievada "7", programma veiks USD → EUR konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value * USD_TO_EUR # Šī rindiņa veic konvertēšanu, reizinot ievadīto vērtību (value) ar USD_TO_EUR konstantu, kas ir konvertēšanas koeficients no ASV dolāriem uz eiro. Rezultāts tiek saglabāts mainīgajā "result". Piemēram, ja lietotājs ievada 10 USD, tad result būs 10 * 0.84235020 = 8.4235 EUR.
    print(f"{value:.2f} USD = {result:.2f} EUR") # Šī rindiņa izvada rezultātu formātā "X USD = Y EUR", kur X ir ievadītā vērtība (value) ar divām zīmēm aiz komata, un Y ir konvertētā vērtība (result) ar divām zīmēm aiz komata. f-string sintakse ļauj ērti formatēt tekstu un mainīgos vienā rindiņā. Piemēram, ja value ir 10 un result ir 8.4235, tad izvadītais teksts būs "10.00 USD = 8.42 EUR". Tas padara rezultātu skaidru un viegli saprotamu lietotājam.

elif choice == "8": # Šis elif bloks pārbauda, vai lietotāja izvēle ir "8", kas atbilst EUR → USD konvertēšanai. Ja izvēle ir "8", programma veic konvertēšanu, dalot ievadīto vērtību ar USD_TO_EUR konstantu, un izvada rezultātu formātā "X EUR = Y USD". Ja izvēle nav "8", programma turpina pārbaudīt citas iespējas ar elif blokiem. "8" ir teksta virkne, nevis skaitlis, jo input() funkcija vienmēr atgriež tekstu. Tāpēc mēs salīdzinām choice ar teksta virkni "8", nevis ar skaitli 8. Ja lietotājs ievada "8", programma veiks EUR → USD konvertēšanu. Ja lietotājs ievada citu numuru, programma pārbaudīs citas iespējas un veiks attiecīgo konvertēšanu, ja tāda būs izvēlēta. Ja neviena no iespējām neatbilst lietotāja izvēlei, programma izvadīs ziņojumu "Nepareiza izvēle!".
    result = value / USD_TO_EUR # Šī rindiņa veic konvertēšanu, dalot ievadīto vērtību (value) ar USD_TO_EUR konstantu, kas ir konvertēšanas koeficients no ASV dolāriem uz eiro. Rezultāts tiek saglabāts mainīgajā "result". Piemēram, ja lietotājs ievada 10 EUR, tad result būs 10 / 0.84235020 = 11.8701 USD.
    print(f"{value:.2f} EUR = {result:.2f} USD") # Šī rindiņa izvada rezultātu formātā "X EUR = Y USD", kur X ir ievadītā vērtība (value) ar divām zīmēm aiz komata, un Y ir konvertētā vērtība (result) ar divām zīmēm aiz komata. f-string sintakse ļauj ērti formatēt tekstu un mainīgos vienā rindiņā. Piemēram, ja value ir 10 un result ir 11.8701, tad izvadītais teksts būs "10.00 EUR = 11.87 USD". Tas padara rezultātu skaidru un viegli saprotamu lietotājam.

else: # Šis else bloks tiek izpildīts, ja neviena no iepriekšējām if vai elif nosacījumiem nav patiess. Tas nozīmē, ka lietotājs ir ievadījis numuru, kas nav no 1 līdz 8, vai ir ievadījis nepareizu vērtību. Ja tas notiek, programma izvadīs ziņojumu "Nepareiza izvēle!" un pēc tam tiks pārtraukta ar exit() funkciju. Tas nodrošina, ka programma darbojas tikai ar derīgām izvēlēm un sniedz lietotājam atgriezenisko saiti par nepareizu izvēli.
    print("Nepareiza izvēle!") # Šī rindiņa izvada ziņojumu "Nepareiza izvēle!", ja lietotājs ir ievadījis numuru, kas nav no 1 līdz 8, vai ir ievadījis nepareizu vērtību. Tas sniedz lietotājam atgriezenisko saiti par nepareizu izvēli un palīdz viņam saprast, ka viņam jāievada derīgs numurs, lai programma varētu veikt konvertēšanu. Pēc šīs rindiņas programma tiks pārtraukta ar exit() funkciju, lai novērstu turpmāku izpildi ar nepareizu izvēli.
